CREATE TABLE public.test_fin
(
	ein integer NOT NULL,
	tax_year integer NOT NULL,
	cash money,

	-- Crawled financials data
	receivables_inventories_prepaids money,
	short_term_investments money,
	other_current_assets money,
	total_current_assets money,
	long_term_investments money,
	fixed_assets money,
	other_long_term_assets money,
	total_long_term_assets money,
	total_assets money,
	payables_and_accrued_expenses money,
	other_current_liabilities money,
	total_current_liabilities money,
	debt money,
	due_to_from_affiliates money,
	other_long_term_liabilities money,
	total_long_term_liabilities money,
	total_liabilities money,
	without_donor_restrictions money,
	with_donor_restrictions money,
	net_assets money,
	total_contributions money,
	program_service_revenue money,
	membership_dues money,
	investment_income money,
	other_revenue money,
	total_other_revenue money,
	total_revenue money,
	program_services money,
	management_and_general money,
	fundraising money,
	total_expenses money,
	surplus_deficit money,
	other_changes_in_net_assets money,
	total_change_in_net_assets money,

	PRIMARY KEY(ein, tax_year)
)
