CREATE VIEW public.pretty_financials
AS

SELECT charities.charity_name,
	charities.sector,
	financials.ein,
	tax_year,
	cash,
	receivables_inventories_prepaids,
	short_term_investments,
	other_current_assets,
	total_current_assets,
	long_term_investments,
	fixed_assets,
	other_long_term_assets,
	total_long_term_assets,
	total_assets,
	payables_and_accrued_expenses,
	other_current_liabilities,
	total_current_liabilities,
	debt,
	due_to_from_affiliates,
	other_long_term_liabilities,
	total_long_term_liabilities,
	total_liabilities,
	without_donor_restrictions,
	with_donor_restrictions,
	net_assets,
	total_contributions,
	program_service_revenue,
	membership_dues,
	investment_income,
	other_revenue,
	total_other_revenue,
	total_revenue,
	program_services,
	management_and_general,
	fundraising,
	total_expenses,
	surplus_deficit,
	other_changes_in_net_assets,
	total_change_in_net_assets,
	gen_admin_expenses,
	fundraising_cost_ratio,
	contribution_reliance_ratio,
	spending_ratio,
	program_output_ratio,
	degree_of_lt_investment,
	cur_asset_turnover,
	program_expense_ratio,
	gen_admin_expense_ratio,
	fundraising_expense_ratio,
	gen_admin_revenue_ratio,
	fundraising_revenue_ratio,
	savings_revenue_ratio,
	return_on_fr_effort,
	other_revenue_reliance,
	total_asset_turnover,
	reserve_accumulation_rate,
	liabilities_ratio,
	reserve_coverage_ratio
FROM financials
LEFT JOIN charities ON charities.ein = financials.ein
WHERE financials.tax_year > 2015
	AND total_current_assets <> 0::money
	AND total_assets <> 0::money
	AND gen_admin_expenses <> 0::money
ORDER BY charity_name, tax_year DESC;
